name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'runpod_handler.py'
      - 'Dockerfile.runpod'
      - 'requirements.txt'
      - 'install.py'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:  # 允许手动触发

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/facefusion-runpod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # 确保下载 LFS 文件

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Verify model files
        run: |
          echo "Verifying model files are actual files, not LFS pointers:"
          ls -lh .assets/models/*.onnx || echo "No model files found"
          echo "Total model directory size:"
          du -sh .assets/models/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.runpod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Image digest
        run: |
          echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
          echo "Image tags: ${{ steps.meta.outputs.tags }}"